PROJECT=asm
CPU ?= cortex-m3
BOARD ?= stm32vldiscovery

qemu:
	arm-none-eabi-as -mthumb -mcpu=$(CPU) -ggdb -c asm.s -o asm.o
	arm-none-eabi-ld -Tmap.ld asm.o -o asm.elf
	arm-none-eabi-objdump -D -S asm.elf > asm.elf.lst
	arm-none-eabi-readelf -a asm.elf > asm.elf.debug
	qemu-system-arm -S -M $(BOARD) -cpu $(CPU) -nographic -kernel $(PROJECT).elf -gdb tcp::1234

gdb:
	gdb-multiarch -q $(PROJECT).elf -ex "target remote localhost:1234"

clean:
	rm -rf *.out *.elf .gdb_history *.lst *.debug *.o


